services:
  consul:
    # Pinning a specific version avoids the "manifest unknown" error
    image: consul:1.15.4
    network_mode: "host"
     
    environment:
      - CONSUL_BIND_INTERFACE=eth0


  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: auth_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: